algo = input("Digite algo: ")
print(f"O tipo primitivo desse valor é {type(algo)}")
print(f"Só tem espaços? {algo.isspace()}")
print(f"É um número? {algo.isnumeric()}")
print(f"É alfabeto? {algo.isalpha()}")
print(f"É alfanumerico? {algo.isalnum()}")
print(f"Está em maiúsculas? {algo.isupper()}")
print(f"Está em minusculas? {algo.islower()}")
print(f"Está capitalizada? {algo.istitle()}")
